name: Build

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  test:
    name: node v${{ matrix.node }}, pptr ${{ matrix.puppeteer_version }}, ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 18
        puppeteer_version:
          - 20.3.0 # 2022-01-17 - Chromium 98.0.4758.0

        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        uses: bahmutov/npm-install@v1 # basically npm ci with a cache
      - run: npm install puppeteer@${{ matrix.puppeteer_version }}
      # - run: npm test
      - run: npm run coverage
      - name: Collect coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run_node-v${{ matrix.node }}_pptr-${{ matrix.puppeteer_version }}_os-${{ matrix.os }}
          parallel: true

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Report coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: report-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: npm ci
        uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
